### ISSUE TITLE
Mechanic 1.0.4 + RoboFont 1.7b (built 1504171012)

### ISSUE THREAD

**Issue by LaPolice** [jackjennings/Mechanic#13] opened 2015-04-20 07:56 UTC
Hi Jack,

After installing an update, the window sticks and if I click again to check for updates, another Mechanic window pops up. Your extension works fine and does the job but I thought I should report this behaviour.
I'm running 10.9.5.

Thanks & best,

Mathieu

**Comment by rbmntjs** [comment] 2015-05-20 10:22
This happens also on Yosemite. In my case, the window cannot be closed again. Just sits there.

![screen shot 2015-05-20 at 12 20 42](https://cloud.githubusercontent.com/assets/49890/7723699/d85aff52-feea-11e4-8a82-f2aa7a09dd4e.png)

**Comment by jackjennings** [comment] 2015-05-20 15:37
Do either of you get a stack trace in the output window when this happens? @rbmntjs Are you running the beta as well?

**Comment by jackjennings** [comment] 2015-05-20 15:39
I admit that I'm not spending a lot of time in RoboFont these days, which is probably required to reproduce this. Can you both let me know about how many extensions you have installed as well, please?

**Comment by LaPolice** [comment] 2015-05-20 19:38
What a coincidence, just saw you message and Mechanic notified me of an update for 1 extension. Did you trigger something via a secret extension remote control, or what?
I get two windows but once the update is done, I can close the window. From the Output window I read: Deprecated: use 'buildAdditionContextualMenuItems'.
I'm using the latest beta (Version 1.7b (built 1505182242)) on 10.9.5.

**Comment by LaPolice** [comment] 2015-05-20 20:17
Sorry, missed you last question: 47 extensions on my side. I know, I know, I enjoy testing…

**Comment by rbmntjs** [comment] 2015-05-21 09:30
I don’t get any stack trace. I’m using the latest RoboFont stable on latest Yosemite. I have about 25 extensions.

**Comment by jackjennings** [comment] 2015-05-21 15:14
Alright, thanks guys. I'm looking into it.

@LaPolice: yes, what you secretly don't know is that everyone releasing extensions is actually just a vast bot net controlled by the mechanic server.

**Comment by jackjennings** [comment] 2016-02-18 20:55
Hey @rbmntjs, @LaPolice: I know that this was logged a long time ago. Are either of you still running with Mechanic enabled, and can you confirm that the same issue is still occurring on the most recent build (1.3.3)?

**Comment by LaPolice** [comment] 2016-02-19 13:19
Hello Jack, thanks for the follow-up. 
I've just installed the latest Mechanic build along the RF's freshest one (1.7b (built 1602122157)). 
When I launch Mechanic to check for updates: I get "Install 10 Updates" in the main window, as well as 2 shorter windows with the same message "Updates are available for 10 of your extensions".
If I click "Show Details" for both of them, the same content is listed in two separate windows.
Then, if I click any of the 3 "Install 10 Updates" buttons, all updates are performed smoothly (thanks). Once the task is completed, the list in the window disappears. The 2 remaining windows still display the list of updates though.
Finally, I close all three windows, knowing that even though I see lists of updates, they've been done successfully.
If I ask Mechanic to check for updates again, only one window shows up with no updates listed.

**Comment by jackjennings** [comment] 2016-02-19 18:53
OK, so it sounds like the lingering issue is probably related to #17? Really there should only be one window open at a time ever, but I do need to rewrite some of how this works to make that happen, since the standard vanilla/RoboFont implementation of won't work with Mechanic (as far as I know).

**Comment by LaPolice** [comment] 2016-02-20 11:07
What Jeremie is reporting at [#17](https://github.com/jackjennings/Mechanic/issues/17) sound familiar indeed. As long as the updates are working, I can live with two windows until you find the time to fix it.

**Comment by jackjennings** [comment] 2016-02-20 18:48
OK, I'm going to close this issue as fixed. Thanks for reporting it, and let me know if you have any other issues.

**Closed by jackjennings** 2016-02-20 18:48 UTC
